import React from "react";

const Clients = () => {
  return (
    <>
      <div
        data-w-id="13ce6919-8d5a-7d43-7f33-1e18cf5ac44c"
        style={{ opacity: 1 }}
        className="partner-container spacing-partner"
      >
        <div className="heading-wrapper">
          <h2 className="sub-titile_new-2">Some of our clients</h2>
        </div>
      </div>
      <div className="section-logo-marquee padding-horizontal-vertical">
        <div className="marquee">
          <div className="marquee-content scroll">
            <img
              src="/assets/imgs/HDFC.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Groww.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Bajaj-Finserve.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/B612.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Alibabagroup.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Cred.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Tata-1mg.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Urban-company.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
          </div>
          <div className="marquee-content scroll">
            <img
              src="/assets/imgs/Kotak.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Dunzo.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Dream11.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Airtel.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/ZEE.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/OYO.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Josh.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Share-Chat.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
          </div>
          <div className="marquee-content scroll">
            <img
              src="/assets/imgs/Make-My-Trip.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Goibibo.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/ixigo.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Yatra.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Nykaa.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Myntra.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Snapdeal.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="https://uploads-ssl.webflow.com/63806eb7687817f7f9be26de/6464b1e584df30bdd28524bc_Smood.ch%20PINK.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
          </div>
          <div className="marquee-content scroll">
            <img
              src="/assets/imgs/IDFC.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Yes-Bank.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Edelweiss.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/ELSA.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/CoinMArketcap.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/SimpleLearn.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/BYJUs-Exam-Prep.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/mint.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
          </div>
          <div className="marquee-content scroll">
            <img
              src="/assets/imgs/Magicbricks.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Housing.com.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Nobroker.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Ultrahuman.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Fynd.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Fancode.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/fectar.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/One-code_ZET.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
          </div>
          <div className="marquee-content scroll">
            <img
              src="/assets/imgs/HDFC.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Groww.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Bajaj-Finserve.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/B612.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Alibabagroup.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Cred.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Tata-1mg.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
            <img
              src="/assets/imgs/Urban-company.svg"
              loading="eager"
              width="120"
              alt=""
              className="marquee-image"
            />
          </div>
        </div>
      </div>
      <div
        data-w-id="1d6fa538-76d2-a785-245f-450676df0449"
        className="logo-carousel-container-2"
      >
        <div className="carousel-2">
          <div
            style={{
              WebkitTransform:
                "translate3d(0%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)",
              MozTransform:
                "translate3d(0%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)",
              msTransform:
                "translate3d(0%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)",
              transform:
                "translate3d(0%, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)",
            }}
            className="logo-carousel-wrapper-2"
          >
            <div className="logo-loop-container-2">
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/HDFC.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Groww.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Bajaj-Finserve.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/B612.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Alibabagroup.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Cred.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Tata-1mg.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Urban-company.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Kotak.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Dunzo.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Dream11.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Airtel.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/ZEE.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/OYO.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Josh.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Share-Chat.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Make-My-Trip.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Goibibo.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/ixigo.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Yatra.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Nykaa.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Myntra.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Snapdeal.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Smood.ch-PINK.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/IDFC.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Yes-Bank.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Edelweiss.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/ELSA.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/CoinMArketcap.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/SimpleLearn.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/BYJUs-Exam-Prep.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/mint.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Magicbricks.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Nobroker.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Ultrahuman.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Fynd.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
              <div className="item-holder-2">
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/Fancode.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/fectar.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/One-code_ZET.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/netmeds.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
                <div className="logo-item-2">
                  <img
                    src="/assets/imgs/FreshMenu.svg"
                    loading="lazy"
                    width="100"
                    alt=""
                    className="image-logos"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Clients;
