import Header from "../components/Header";
import Footer from "../components/Footer";
import Head from "next/head";
import Audit from "../components/Audit";
import Solutions from "../components/Solutions";
import Testimonials from "../components/Testimonials";
import OurPricing from "../components/OurPricing";
import ASOTools from "../components/ASOTools";
import AppIntelligence from "../components/AppIntelligence";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Labs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        <Audit />
        <Solutions />
        <Testimonials />
        <OurPricing />
        <ASOTools />
        <AppIntelligence />
        <Footer />
      </main>
    </>
  );
}
