import Header from "../components/Header";
import Footer from "../components/Footer";
import Head from "next/head";
import Audit from "../components/Audit";
import Solutions from "../components/Solutions";
import Testimonials from "../components/Testimonials";
import OurPricing from "../components/OurPricing";
import ASOTools from "../components/ASOTools";
import AppIntelligence from "../components/AppIntelligence";
import Other from "../components/Other";
import ContactForm from "../components/ContactForm";
import Clients from "../components/Clients";
import LoginPopup from "../components/elements/LoginPopup";
export default function Home() {
  return (
    <>
      <Head>
        <title>App Store Optimization Services | ASO Agency | ASO Company India</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        {/* <LoginPopup /> */}
        <Audit />
        <Clients />
        <Solutions />
        <Testimonials />
        {/* <OurPricing /> */}
        <ASOTools />
        <AppIntelligence />
        <Other />
        <ContactForm />
        <Footer />
      </main>
    </>
  );
}
